export const image ={
    welcome:require('../assests/welcome.png'),
    loginbg:require('../assests/loginbgm.png'),
    logo:require('../assests/logo.png'),
    seachicon:require('../assests/searchicon.png'),
    cancelicon:require('../assests/cancelicon.png'),
    profilelogo:require('../assests/profilelogo.png'),
    backarrows:require('../assests/backarrow.png'),
    whiteimg:require('../assests/profilelogo.png'),
    chat:require('../assests/chat.png'),
    home:require('../assests/home.png'),
    livechat:require('../assests/livechat.png'),
    sendicon:require('../assests/sendicon.png'),
    callicon:require('../assests/callicon.png'),
    videoicon:require('../assests/videoicon.png'),
    threedot:require('../assests/threedot.png'),
    seachiconn:require('../assests/searchiconn.png'),
    addedfrnicn:require('../assests/addedfrnicn.png'),
    post:require('../assests/post.png'),
    heart:require('../assests/heart.png'),
    goto:require('../assests/goto.png'),
    search:require('../assests/search.png'),
    bell2:require('../assests/bell2.png'),
    message2:require('../assests/message2.png'),
    doubletick:require('../assests/tick.png'),
    
    
}